download fix10

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -23,29 +23,18 @@ jobs:
           name: wait for localhost
           shell: /bin/sh
           command: wget --waitretry=3 --tries=40 --timeout=5 --retry-connrefused --spider --quiet http://localhost:3000
-      # - run: 
-      #     name: Cypress Tests
-      #     command: |
-      #       set +e
-      #       npm run cy:run
-      #       # Check the exit status of tests
-      #       CURR_STATUS=$?
-      #       if [[ $CURR_STATUS -ne 0 ]]; then
-      #       echo "EXIT_CODE=1" >> $BASH_ENV
-      #       fi
-      #       set -e
 
       - run:
-          name: Updating Baseline
+          name: cypress tests and current differences
           command: |
-            set +e
+            # set +e
             python3 circleciUpdate.py
-            # Check the exit status of tests
-            CURR_STATUS=$?
-            if [[ $CURR_STATUS -ne 0 ]]; then
-            echo "EXIT_CODE=1" >> $BASH_ENV
-            fi
-            set -e
+            # # Check the exit status of tests
+            # CURR_STATUS=$?
+            # if [[ $CURR_STATUS -ne 0 ]]; then
+            # echo "EXIT_CODE=1" >> $BASH_ENV
+            # fi
+            # set -e
 
       - store_artifacts:
           path: ~/cypress-circleci-snapshot/cypress-visual-screenshots/comparison
