download fix9

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -37,7 +37,15 @@ jobs:
 
       - run:
           name: Updating Baseline
-          command: python3 circleciUpdate.py
+          command: |
+            set +e
+            python3 circleciUpdate.py
+            # Check the exit status of tests
+            CURR_STATUS=$?
+            if [[ $CURR_STATUS -ne 0 ]]; then
+            echo "EXIT_CODE=1" >> $BASH_ENV
+            fi
+            set -e
 
       - store_artifacts:
           path: ~/cypress-circleci-snapshot/cypress-visual-screenshots/comparison
