fix44

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -24,9 +24,10 @@ jobs:
           name: Cypress Tests
           command: |
             set +e
+            trap 'exit 1' ERR
             npm run cyr:run
-            EXIT_STATUS=$?
-            echo "Exit status of your-command-1: $EXIT_STATUS"
+            # EXIT_STATUS=$?
+            # echo "Exit status of your-command-1: $EXIT_STATUS"
       - run:
           name: Commit and push code
           command: |
@@ -36,10 +37,9 @@ jobs:
             git commit -m "CircleCI automatic commit" || true
             git push origin main || true
 
-            if [[ $EXIT_STATUS -ne 0 ]]; then
-              exit 1
-            fi
-
+            # if [[ $EXIT_STATUS -ne 0 ]]; then
+            #   exit 1
+            # fi
             exit 0
 
 workflows:
